site_name: Medpipe
theme:
  name: material
  palette:
    scheme: slate # Dark mode; remove this line for light mode
  features:
    - navigation.sections
    - navigation.expand

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - include-markdown
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            docstring_style: numpy


nav:
  - Home: index.md
  - Getting started:
    - Installation: start/install.md
    - Quickstart example: start/quickstart.md
  - User guides:
    - Configuration guide: guide/config.md
  - API reference:
    - Data: api/data.md
    - Metrics: api/metrics.md
    - Models: api/models.md
    - Pipeline: api/pipeline.md
    - Utils: api/utils.md
    - Visualisation: api/visualisation.md
