[project]
name = "medpipe"
version = "0.3.1"
description = "A package for clinical AI pipeline development"
readme = "README.md"
requires-python = ">=3.12"
license = "Apache-2.0"
license-files = ["LICEN[CS]E*"]
authors = [
  { name = "Mathias Roesler", email = "mathias.roesler@auckland.co.nz" },
]
classifiers = [
  "Operating System :: POSIX :: Linux",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dynamic = ["dependencies"]

[project.urls]
Changelog = "https://github.com/https://github.com/Surgical-Recovery-and-Safety-Lab/medpipe/blob/main/CHANGELOG.md"
Homepage = "https://github.com/Surgical-Recovery-and-Safety-Lab/medpipe"

[build-system]
requires = ["setuptools>=80.9"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "" = "src" }
packages = [
  "medpipe",
  "medpipe.data",
  "medpipe.models",
  "medpipe.metrics",
  "medpipe.pipeline",
  "medpipe.utils"
]
dynamic.dependencies = { file = ["requirements.txt"] }
