[build-system]
build-backend = "setuptools.build_meta"
requires = [ "setuptools>=80.9" ]

[project]
name = "medpipe"
version = "0.2.0.dev0"
description = "A package for clinical AI pipeline development"
readme = "README.md"
license = "Apache-2.0"
license-files = [ "LICEN[CS]E*" ]
authors = [
  { name = "Mathias Roesler", email = "mathias.roesler@auckland.co.nz" },
]
requires-python = ">=3.12"
classifiers = [
  "Operating System :: POSIX :: Linux",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dynamic = [ "dependencies" ]
urls.Repository = "https://github.com/Surgical-Recovery-and-Safety-Lab/medpipe"

[tool.setuptools]
package-dir = { "" = "src" }
packages = [ "medpipe", "medpipe.data", "medpipe.models", "medpipe.metrics", "medpipe.pipeline", "medpipe.utils" ]
dynamic.dependencies = { file = [ "requirements.txt" ] }
