[build-system]
build-backend = "setuptools.build_meta"
requires = [ "setuptools>=80.9" ]

[project]
name = "pyrisk"
version = "0.0.1"
description = "A package for AI risk score model development"
readme = "README.md"
license = "Apache-2.0"
license-files = [ "LICEN[CS]E*" ]
authors = [
  { name = "Mathias Roesler", email = "mathias.roesler@auckland.co.nz" },
]
requires-python = ">=3.12"
classifiers = [
  "Operating System :: Linux",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]

dynamic = [ "dependencies" ]
urls.Repository = "https://github.com/Surgical-Recovery-and-Safety-Lab/pyrisk"

[tool.setuptools.dynamic]
dependencies = { file = [ "requirements.txt" ] }
