[meta]
project_name = "ai_risk_HGBc"
run_mode = "fast"

[data]
path = "/home/mroe734/Documents/srs/medpipe/test/test_data.csv"
predictors = [
  "AGE",
  "SEX",
  "PRIOR_CANCER",
  "ADMISSION_ACUITY",
  "ADMISSION_SOURCE",
  "CATEGORY_LEVEL_1",
  "OP_SEVERITY",
]
outcomes = ["MORTALITY_30D", "ANY_COMP"]

# ------------------------------------------------------------------------------
# DEFAULT MODEL SETUP
# ------------------------------------------------------------------------------
[default_model]
algorithm = "HistGradientBoostingClassifier"

[default_model.hyperparameters]
learning_rate = 0.1
loss = "log_loss"
max_features = 0.2

[default_model.recalibration]
method = "isotonic"

[default_model.recalibration.hyperparameters]
y_min = 0.0
y_max = 1.0
out_of_bounds = "clip"

# ------------------------------------------------------------------------------
# OUTCOME OVERRIDES
# ------------------------------------------------------------------------------
[outcome_overrides.ANY_COMP]
algorithm = "GradientBoostingClassifier"

[outcome_overrides.ANY_COMP.hyperparameters]
learning_rate = 0.1
max_depth = 10

# Override the recalibration method and its specific hyperparameters for ANY_COMP
[outcome_overrides.ANY_COMP.recalibration]
method = "isotonic"

# ------------------------------------------------------------------------------
# WORKFLOW
# ------------------------------------------------------------------------------
[workflow]
random_state = 42

[workflow.preprocessing]
preprocess = true
operations = [
  { name = "OrdinalEncoder", columns = [
    "SEX",
    "ADMISSION_ACUITY",
    "ADMISSION_SOURCE",
    "CATEGORY_LEVEL_1"
  ] },
  { name = "StandardScaler", columns = ["CATEGORY_LEVEL_1", "AGE"], with_mean = true },
]

[workflow.validation.test_split]
strategy = "group"
group_column = "OP_YEAR"
values = [2024]

[workflow.validation.recalibration_split]
strategy = "group"
group_column = "OP_YEAR"
values = [2023]

[workflow.validation.cross_validation]
strategy = "group"
group_column = "DHB_NAME"
n_splits = 3
shuffle = true

[workflow.evaluation.metrics]
metrics = ["roc_auc", "log_loss"]
n_bootstraps = 1000
ci_level = 0.95

[workflow.evaluation.calibration]
strategy = "spline"
n_bootstraps = 2

[workflow.evaluation.fairness]
strata = ["SEX", "AGE"]
groups = { "AGE" = [[18, 50], [51, 120]] }
